services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app
    ports:
      - "3000:3000"
      - "443:443"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "node", "new_app.js"]
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: hospitaldb

  db:
    image: mariadb:10.6
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: hospitaldb
    ports:
      - "3306:3306"
    command: --max_allowed_packet=734003200
    volumes:
      - db_data:/var/lib/mysql
      - ./database/asrpatientinfo.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
